=== api-evangelist/amazon-polly/json-schema/amazon-polly-synthesis-task-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-polly/refs/heads/main/json-schema/amazon-polly-synthesis-task-schema.json",
  "title": "SynthesisTask",
  "description": "SynthesisTask object that provides information about a speech synthesis task.",
  "type": "object",
  "properties": {
    "Engine": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Engine"
        },
        {
          "description": "Specifies the engine (<code>standard</code> or <code>neural</code>) for Amazon Polly to use when processing input text for speech synthesis. Using a voice that is not supported for the engine selected will result in an error."
        }
      ]
    },
    "TaskId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TaskId"
        },
        {
          "description": "The Amazon Polly generated identifier for a speech synthesis task."
        }
      ]
    },
    "TaskStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TaskStatus"
        },
        {
          "description": "Current status of the individual speech synthesis task."
        }
      ]
    },
    "TaskStatusReason": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TaskStatusReason"
        },
        {
          "description": "Reason for the current status of a specific speech synthesis task, including errors if the task has failed."
        }
      ]
    },
    "OutputUri": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputUri"
        },
        {
          "description": "Pathway for the output speech file."
        }
      ]
    },
    "CreationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "Timestamp for the time the synthesis task was started."
        }
      ]
    },
    "RequestCharacters": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RequestCharacters"
        },
        {
          "description": "Number of billable characters synthesized."
        }
      ]
    },
    "SnsTopicArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnsTopicArn"
        },
        {
          "description": "ARN for the SNS topic optionally used for providing status notification for a speech synthesis task."
        }
      ]
    },
    "LexiconNames": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LexiconNameList"
        },
        {
          "description": "List of one or more pronunciation lexicon names you want the service to apply during synthesis. Lexicons are applied only if the language of the lexicon is the same as the language of the voice. "
        }
      ]
    },
    "OutputFormat": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputFormat"
        },
        {
          "description": "The format in which the returned output will be encoded. For audio stream, this will be mp3, ogg_vorbis, or pcm. For speech marks, this will be json. "
        }
      ]
    },
    "SampleRate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SampleRate"
        },
        {
          "description": "<p>The audio frequency specified in Hz.</p> <p>The valid values for mp3 and ogg_vorbis are \"8000\", \"16000\", \"22050\", and \"24000\". The default value for standard voices is \"22050\". The default value for neural voices is \"24000\".</p> <p>Valid values for pcm are \"8000\" and \"16000\" The default value is \"16000\". </p>"
        }
      ]
    },
    "SpeechMarkTypes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SpeechMarkTypeList"
        },
        {
          "description": "The type of speech marks returned for the input text."
        }
      ]
    },
    "TextType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TextType"
        },
        {
          "description": "Specifies whether the input text is plain text or SSML. The default value is plain text. "
        }
      ]
    },
    "VoiceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VoiceId"
        },
        {
          "description": "Voice ID to use for the synthesis. "
        }
      ]
    },
    "LanguageCode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LanguageCode"
        },
        {
          "description": "<p>Optional language code for a synthesis task. This is only necessary if using a bilingual voice, such as Aditi, which can be used for either Indian English (en-IN) or Hindi (hi-IN). </p> <p>If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice. The default language for any voice is the one returned by the <a href=\"https://docs.aws.amazon.com/polly/latest/dg/API_DescribeVoices.html\">DescribeVoices</a> operation for the <code>LanguageCode</code> parameter. For example, if no language code is specified, Aditi will use Indian English rather than Hindi.</p>"
        }
      ]
    }
  }
}

=== api-evangelist/amazon-polly/examples/amazon-polly-synthesis-task-example.json
{
  "Engine": "neural",
  "TaskId": "voice-382",
  "TaskStatus": "example-TaskStatus",
  "TaskStatusReason": "example-TaskStatusReason",
  "OutputUri": "mp3",
  "CreationTime": "example-CreationTime",
  "RequestCharacters": "example-RequestCharacters",
  "SnsTopicArn": "example-SnsTopicArn",
  "LexiconNames": "Joanna",
  "OutputFormat": "mp3",
  "SampleRate": "example-SampleRate",
  "SpeechMarkTypes": "example-SpeechMarkTypes",
  "TextType": "Hello, this is a sample text for speech synthesis.",
  "VoiceId": "voice-393",
  "LanguageCode": "en-US"
}
