=== api-evangelist/amazon-polly/json-schema/amazon-polly-start-speech-synthesis-task-input-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-polly/refs/heads/main/json-schema/amazon-polly-start-speech-synthesis-task-input-schema.json",
  "title": "StartSpeechSynthesisTaskInput",
  "description": "StartSpeechSynthesisTaskInput schema from Amazon Polly API",
  "type": "object",
  "properties": {
    "Engine": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Engine"
        },
        {
          "description": "Specifies the engine (<code>standard</code> or <code>neural</code>) for Amazon Polly to use when processing input text for speech synthesis. Using a voice that is not supported for the engine selected will result in an error."
        }
      ]
    },
    "LanguageCode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LanguageCode"
        },
        {
          "description": "<p>Optional language code for the Speech Synthesis request. This is only necessary if using a bilingual voice, such as Aditi, which can be used for either Indian English (en-IN) or Hindi (hi-IN). </p> <p>If a bilingual voice is used and no language code is specified, Amazon Polly uses the default language of the bilingual voice. The default language for any voice is the one returned by the <a href=\"https://docs.aws.amazon.com/polly/latest/dg/API_DescribeVoices.html\">DescribeVoices</a> operation for the <code>LanguageCode</code> parameter. For example, if no language code is specified, Aditi will use Indian English rather than Hindi.</p>"
        }
      ]
    },
    "LexiconNames": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LexiconNameList"
        },
        {
          "description": "List of one or more pronunciation lexicon names you want the service to apply during synthesis. Lexicons are applied only if the language of the lexicon is the same as the language of the voice. "
        }
      ]
    },
    "OutputFormat": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputFormat"
        },
        {
          "description": "The format in which the returned output will be encoded. For audio stream, this will be mp3, ogg_vorbis, or pcm. For speech marks, this will be json. "
        }
      ]
    },
    "OutputS3BucketName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputS3BucketName"
        },
        {
          "description": "Amazon S3 bucket name to which the output file will be saved."
        }
      ]
    },
    "OutputS3KeyPrefix": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputS3KeyPrefix"
        },
        {
          "description": "The Amazon S3 key prefix for the output speech file."
        }
      ]
    },
    "SampleRate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SampleRate"
        },
        {
          "description": "<p>The audio frequency specified in Hz.</p> <p>The valid values for mp3 and ogg_vorbis are \"8000\", \"16000\", \"22050\", and \"24000\". The default value for standard voices is \"22050\". The default value for neural voices is \"24000\".</p> <p>Valid values for pcm are \"8000\" and \"16000\" The default value is \"16000\". </p>"
        }
      ]
    },
    "SnsTopicArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnsTopicArn"
        },
        {
          "description": "ARN for the SNS topic optionally used for providing status notification for a speech synthesis task."
        }
      ]
    },
    "SpeechMarkTypes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SpeechMarkTypeList"
        },
        {
          "description": "The type of speech marks returned for the input text."
        }
      ]
    },
    "Text": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Text"
        },
        {
          "description": "The input text to synthesize. If you specify ssml as the TextType, follow the SSML format for the input text. "
        }
      ]
    },
    "TextType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TextType"
        },
        {
          "description": "Specifies whether the input text is plain text or SSML. The default value is plain text. "
        }
      ]
    },
    "VoiceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VoiceId"
        },
        {
          "description": "Voice ID to use for the synthesis. "
        }
      ]
    }
  },
  "required": [
    "OutputFormat",
    "OutputS3BucketName",
    "Text",
    "VoiceId"
  ]
}

=== api-evangelist/amazon-polly/examples/amazon-polly-start-speech-synthesis-task-input-example.json
{
  "Engine": "neural",
  "LanguageCode": "en-US",
  "LexiconNames": "Joanna",
  "OutputFormat": "mp3",
  "OutputS3BucketName": "Joanna",
  "OutputS3KeyPrefix": "mp3",
  "SampleRate": "example-SampleRate",
  "SnsTopicArn": "example-SnsTopicArn",
  "SpeechMarkTypes": "example-SpeechMarkTypes",
  "Text": "Hello, this is a sample text for speech synthesis.",
  "TextType": "Hello, this is a sample text for speech synthesis.",
  "VoiceId": "voice-709"
}
